# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47bf3b4a5b77aabcdb5bc1b5b4952e9ceaaf9ce358546b573fe7755f143a58ca6c094c0835789cbfe64e3d96fe706616779f375409266815558a728fce81bdf9

test:
  secret_key_base: 171c0c7d4056d1cbff8b98ece56c3e0e58f940fd37d00559153d1b1f575bdfef3de288bdefe4b744a8886f665ab5a487a04e34d70ac9b7f23cb7469a27a54976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
